apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: jwt-example-servicex
  namespace: servicex
spec:
  selector:
    matchLabels:
      app: servicex
  jwtRules:
  - issuer: "testing@secure.istio.io"
    jwksUri: "https://raw.githubusercontent.com/istio/istio/release-1.20/security/tools/jwt/samples/jwks.json"
---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: jwt-example-servicey
  namespace: servicey
spec:
  selector:
    matchLabels:
      app: servicey
  jwtRules:
  - issuer: "testing@secure.istio.io"
    jwksUri: "https://raw.githubusercontent.com/istio/istio/release-1.20/security/tools/jwt/samples/jwks.json"

