apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicey-deployment
  namespace: servicey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicey
  template:
    metadata:
      labels:
        app: servicey
    spec:
      containers:
      - name: servicey
        image: s2s
        ports:
        - containerPort: 8080
